import image1 from "../../images/react.svg";
import image2 from "../../images/js.svg";
import blenderimg from "../../images/blender.svg";
import image4 from "../../images/java.svg";

export const objs = [
  {
    id: "JAVASCRIPT",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "JAVASCRIPT",
    headline: "The modern JavaScript course for everyone! ",
    description: "Master JavaScript with projects, challenges and theory",
    buttonlabel: "Get started",
    imgStart: false,
    img: image2,
    alt: "piggi",
    dark: true,
    primary: true,
    darkText: false,
  },

  {
    id: "REACT",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "react",
    headline: "Dive in and learn React.js , Next.js from scratch! ",
    description: "Learn  Hooks, Redux, React Routing, Animations and way more!",
    buttonlabel: "Get started",
    imgStart: true,
    img: image1,
    alt: "car",
    dark: false,
    primary: false,
    darkText: true,
  },
  {
    id: "BLENDER",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "BLENDER",
    headline: "Dive in and learn React.js , Next.js from scratch! ",
    description: "Learn  Hooks, Redux, React Routing, Animations and way more!",
    buttonlabel: "Get started",
    imgStart: false,
    img: blenderimg,
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
  },

  {
    id: "UNITY",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "UNITY",
    headline: "Code Your first 3D Unity game",
    description: "Design & Develop Video Games. Learn C# in Unity Engine",
    buttonlabel: "Get started",
    imgStart: true,
    img: image1,
    alt: "car",
    dark: false,
    primary: false,
    darkText: true,
  },
  {
    id: "JAVA",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "JAVA",
    headline: "Learn Java In This Course And Become a Computer Programmer",
    description: "Obtain valuable Core Java Skills And Java Certification",
    buttonlabel: "Get started",
    imgStart: false,
    img: image4,
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
  },
];
